version: "3.9"

services:
  psql-db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: jest-psql-example
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
